name: Lint

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: main

env:
  NODE_VERSION: "18.13.0"

jobs:
  lint:
    name: Run code linter
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: npm install

      - name: Lint
        run: npm run ng lint
