# This action will deploy the app to the existing PR environment when a PR is edited.

name: Update PR

on:
  pull_request:
    types: [edited]
    branches: master

env:
  AZURE_WEBAPP_NAME: gccollab-dev-pr-${{ github.event.number }}
  AZURE_WEBAPP_PACKAGE_PATH: './dist/gccollab-frontend'
  NODE_VERSION: '16.14.2'
  SECRET_NAME: PR_${{ github.event.number }}

jobs:
  build-test-and-redeploy:
    name: Build, Test and Redeploy
    runs-on: windows-latest
    environment: 
      name: PR ${{ github.event.number }}
      url: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: npm install

      - name: Build
        run: npm run build-dev --if-present

      - name: Test
        run: npm run test --if-present -- --watch=false --browsers=ChromeHeadless

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v1
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets[env.SECRET_NAME] }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}